---
title: "covid_bootstrapping"
author: "brooke"
date: "7/20/2022"
output: html_document
---


The following script does:


load tidyverse
```{r}
library(tidyverse)
```



Read in the data
Create a summary of the quintile for the shiny table


```{r summarise the quintiles}
covid_census_boots <- read_csv("~/STA 518/BrookemWalters-Portfolio/Stats 518 Final Project/Bootstrapping/covid_census_bs.csv") %>% 
  group_by(covid_mortality_quintile) %>% 
  summarise( 
    `Population Avg` = mean(population19E),
    `Households Avg` = mean(householdsE),          
    `Age Avg` = mean(median_ageE),        
    `HH Income Avg`= mean(median_incomeE),          
    `Percent College Grad Avg` = mean(bach_degree_plus_a25E),               
    `Unemployment Rate Avg` = mean(unemployment_rate),          
    `Percent HHs on Assistance Avg` = mean(public_assist_rate),        
    `Percent Asian Avg` = mean(percent_asian),          
    `Percent Black Avg` = mean(percent_black),               
    `Percent Native American Avg` = mean(percent_native),          
    `Percent Pacific Islander Avg` = mean(percent_pacific_islander),      
    `Percent White Avg` = mean(percent_white),          
    `Percent Hispanic Avg` = mean(percent_hispanic),               
    `Covid Death Avg` = mean(Total_Deaths),          
    `Covid Deaths per Thousand Avg` = mean(Deaths_Per_Pop_Thousand),
  ) %>% 
   mutate_at(2:16, round, 1)
  
covid_census_boots

```

```{r write the file to csv for export for shiny app}

write.csv(covid_census_boots,"~/STA 518/BrookemWalters-Portfolio/Stats 518 Final Project/Tables_Shiny/MIShiny/covid_mortality_summary.csv")
```



